# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{automaze}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Toshiyuki Hirooka"]
  s.date = %q{2010-10-31}
  s.description = %q{maze generator}
  s.email = %q{toshi.hirooka@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/algorithms/boutaoshi.rb",
     "lib/algorithms/dug_tunnels.rb",
     "lib/automaze.rb",
     "lib/panel.rb",
     "sample.rb",
     "spec/automaze_spec.rb",
     "spec/panel_spec.rb"
  ]
  s.homepage = %q{http://github.com/tosik/automazerb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{maze generator}
  s.test_files = [
    "spec/automaze_spec.rb",
     "spec/panel_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

